services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sqlcse312
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432 
    ports:
      - "8080:8080"
    depends_on:
      - postgres
