#services:
#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_DB: sqlcse312
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#  web:
#    build: .
#    environment:
#      WAIT_HOSTS: postgres:5432
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sqlcse312
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432
      SECRET_KEY: 'django-insecure-f*xlhrpkh%xl2cxnsanbw&0qy_q+j*2z1!-dg6rx(s&n75h(w6'
      DB_NAME: sqlcse312
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres