services:
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/
  #     - ./certbot/conf/:/etc/letsencrypt/
  nginx:
    build: ./nginx
    ports: 
      - '80:80'
      - '443:443'
    depends_on:
      - web
    volumes:
    - media_volume:/home/app/web/media
    - static_volume:/home/app/web/static_files
    # - ./nginx/conf/:/etc/nginx/conf.d/:ro
    # - ./certbot/www:/var/www/certbot/:ro
    # - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
  redis:
    image: redis:6.2-alpine
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sqlcse312
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
  web:
    build: .
    environment:
      WAIT_HOSTS: postgres:5432
      SECRET_KEY: Replace Me
      DB_NAME: sqlcse312
      DB_USER: user 
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
     - '8080:8080'
    depends_on:
      - postgres
    volumes:
    - media_volume:/home/app/web/media
    - static_volume:/home/app/web/static_files
    restart: always
volumes:
  static_volume:
  media_volume: