# Generated by Django 5.1.3 on 2024-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('postID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('body', models.CharField(default='', max_length=255)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('parent', models.CharField(max_length=255, null=True)),
                ('replies', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='posts/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
