# Generated by Django 5.1.3 on 2024-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbyID', models.CharField(max_length=255)),
                ('pinLocations', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('lobby', models.CharField(max_length=255)),
                ('time', models.IntegerField(null=True)),
            ],
        ),
    ]
