# Generated by Django 5.1.1 on 2024-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='pinLocations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='solution',
            field=models.TextField(),
        ),
    ]
